spring:
  mvc:
    async:
      request-timeout: -1
  jpa:
    database-platform: com.example.edrone.configuration.SQLDialect
    hibernate.ddl-auto: update
  datasource:
    url: jdbc:sqlite:identifier.sqlite
    driver-class-name: org.sqlite.JDBC
    username: admin
    password: admin

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"